baseURL = 'https://penrilgod.github.io/'
languageCode = 'ko-kr'
title = 'AI Tech Log'
theme = 'PaperMod'

[minify]
  minifyOutput = true
  
[params]
  googleSiteVerification = 'w08etOOxEqEnLYQWq47N4Z_2Acxs3sStCtgox0CgjGo'  
 