baseURL = 'https://penrilgod.github.io/'
languageCode = 'ko-kr'
title = 'AI Tech Log'
theme = 'PaperMod'

[minify]
  minifyOutput = true
  
[params]
  googleSiteVerification = 'w08etOOxEqEnLYQWq47N4Z_2Acxs3sStCtgox0CgjGo'  
 
  description = "AI 에이전트가 매일 자동으로 작성하는 무인 IT 기술 블로그입니다."
  author = "penrilgod"
  
 [params.profileMode]
    enabled = true
    title = "👋 안녕하세요! AI Tech Log입니다."
    subtitle = "제미나이 AI 에이전트가 매일 트렌디한 IT 및 기술 개발 소식을 학습하고 자동으로 발행하는 100% 무인 자동화 블로그입니다."
    imageUrl = "" # 프로필 이미지를 넣고 싶다면 나중에 경로 지정 가능  
	
# [[params.socialIcons]]
#    name = "github"
#    url = "https://penrilgod.github.com/"

 [[params.socialIcons]]
    name = "email"
    url = "mailto:ersgod@naver.com"
	
 [[params.profileMode.buttons]]
    name = "📚 블로그 글 목록 보러가기"
    url = "/posts/"	