name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # main 브랜치에 코드가 올라오면 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          submodules: true  # 테마(PaperMod)까지 함께 가져옴
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true # 테마에 따라 extended 버전이 필요할 수 있음

      - name: Build Site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./public
          publish_branch: gh-pages  # 빌드된 정적 파일이 저장될 브랜치